# Generated by Django 4.2.4 on 2024-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormList',
            fields=[
                ('form_id_list', models.TextField(default='[]', max_length=1024, verbose_name='未处理的申请的id的列表')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='申请处理状态')),
            ],
        ),
    ]
