# Generated by Django 4.2.4 on 2024-12-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=50, verbose_name='OpenAlexID')),
                ('work_name', models.CharField(max_length=100, verbose_name='文章题目')),
                ('number', models.IntegerField(default=0, verbose_name='文章被搜索的次数')),
            ],
        ),
    ]
