# Generated by Django 4.2.4 on 2024-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorks',
            fields=[
                ('work_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='OpenAlexID')),
                ('work_title', models.CharField(max_length=1000, verbose_name='文章题目')),
                ('publication_date', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
    ]
