# Generated by Django 4.2.4 on 2024-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchwork',
            name='id',
        ),
        migrations.AlterField(
            model_name='searchwork',
            name='work_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='OpenAlexID'),
        ),
    ]
