# Generated by Django 4.2.4 on 2024-12-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_searchwork_id_alter_searchwork_work_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchwork',
            old_name='work_name',
            new_name='work_title',
        ),
    ]
