# Generated by Django 4.2.4 on 2024-12-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_searchwork_work_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='搜索词条')),
                ('number', models.IntegerField(default=0, verbose_name='词条被搜索次数')),
            ],
        ),
    ]
