# Generated by Django 4.2.4 on 2024-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_searchword'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorks',
            fields=[
                ('work_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='OpenAlexID')),
                ('created_time', models.DateTimeField(verbose_name='被收录时间')),
            ],
        ),
    ]
