# Generated by Django 4.2.4 on 2024-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='路由信息')),
                ('author_name', models.CharField(max_length=50, verbose_name='作者姓名')),
                ('authorship', models.CharField(max_length=50, verbose_name='作者信息API')),
                ('cited_by_count', models.IntegerField(verbose_name='引用次数')),
                ('created_date', models.DateField(verbose_name='被收录时间')),
                ('openalex_id', models.CharField(max_length=50, verbose_name='OpenAlexID')),
                ('publication_year', models.DateField(verbose_name='发表时间')),
            ],
            options={
                'db_table': 'work_lists',
                'indexes': [models.Index(fields=['author_name'], name='work_lists_author__6f6e9a_idx'), models.Index(fields=['url'], name='work_lists_url_65ec12_idx'), models.Index(fields=['publication_year'], name='work_lists_publica_e20fd5_idx'), models.Index(fields=['cited_by_count'], name='work_lists_cited_b_cba58a_idx')],
            },
        ),
    ]
