# Generated by Django 4.2.4 on 2024-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_work_work_lists_url_65ec12_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='work',
            name='work_lists_openale_be7912_idx',
        ),
        migrations.RemoveField(
            model_name='work',
            name='id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='openalex_id',
        ),
        migrations.AddField(
            model_name='work',
            name='work_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='OpenAlexID'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['work_id'], name='work_lists_work_id_7e8907_idx'),
        ),
    ]
