# Generated by Django 5.1.4 on 2024-12-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户的id')),
                ('list_name', models.CharField(max_length=255, verbose_name='列表名称')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'db_table': 'mark_lists',
                'indexes': [models.Index(fields=['user_id'], name='mark_lists_user_id_a08fdf_idx'), models.Index(fields=['list_name'], name='mark_lists_list_na_4de638_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarkRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(default='', max_length=50, verbose_name='OpenAlexID')),
                ('author_name', models.CharField(default='', max_length=1000, verbose_name='作者姓名')),
                ('mark_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_list', to='mark.mark', verbose_name='标记列表ID')),
            ],
            options={
                'db_table': 'mark_relationships',
                'indexes': [models.Index(fields=['work_id'], name='mark_relati_work_id_b31ebb_idx')],
            },
        ),
    ]
