# Generated by Django 5.1.4 on 2024-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markrelationships',
            name='cited_by_count',
            field=models.IntegerField(default=0, verbose_name='引用次数'),
        ),
        migrations.AddField(
            model_name='markrelationships',
            name='created_date',
            field=models.DateField(default='2024-10-10', verbose_name='被收录时间'),
        ),
        migrations.AddField(
            model_name='markrelationships',
            name='publication_year',
            field=models.DateField(default='2024-10-10', verbose_name='发表时间'),
        ),
        migrations.AddField(
            model_name='markrelationships',
            name='work_title',
            field=models.CharField(default='', max_length=1000, verbose_name='文章题目'),
        ),
    ]
