# Generated by Django 5.1.4 on 2024-12-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_markrelationships_cited_by_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markrelationships',
            old_name='publication_year',
            new_name='publication_date',
        ),
    ]
