# Generated by Django 4.2.4 on 2024-12-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='work',
            name='work_lists_url_65ec12_idx',
        ),
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AlterField(
            model_name='work',
            name='author_name',
            field=models.CharField(max_length=1000, verbose_name='作者姓名'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['openalex_id'], name='work_lists_openale_be7912_idx'),
        ),
    ]
