# Generated by Django 5.1.4 on 2024-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_remove_work_work_lists_url_65ec12_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=1024)),
                ('abstract', models.TextField()),
                ('publish_text', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('publish', models.CharField(max_length=255)),
                ('ref_wr', models.PositiveIntegerField()),
                ('key_words', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': '文献',
                'verbose_name_plural': '文献',
            },
        ),
    ]
