# Generated by Django 5.1.4 on 2024-12-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_literature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalLiteratureCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_literature_count', models.IntegerField()),
            ],
        ),
    ]
