services:
  redis:
    image: redis:alpine
    networks:
      - user_module_network

  user_module:
    image: ghcr.io/edgerunner2233/academiahub-backend-module-user:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    networks:
      - user_module_network

networks:
  user_module_network:
    driver: bridge
