services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - user_module_network

  user_module:
    image: ghcr.nju.edu.cn/edgerunner2233/academiahub-backend-module-user:latest
    depends_on:
      - redis
    restart: always
    ports:
      - "30000:30000"
    environment:
      - REDIS_HOST=redis
      - SECRET_KEY=<SECRET_KEY>
      - MAIL_SERVER=smtp.163.com
      - MAIL_PORT=465
      - MAIL_USE_SSL=True
      - MAIL_USERNAME=AcademiaHub@163.com
      - MAIL_PASSWORD=<MAIL_PASSWORD>
      - MAIL_DEFAULT_SENDER=AcademiaHub@163.com
      - TOKEN_SECRET=<TOKEN_SECRET>
      - TOKEN_EXPIRE_TIME=3600
      - OBS_ACCESS_KEY=<OBS_ACCESS_KEY>
      - OBS_SECRET_KEY=<OBS_SECRET_KEY>
      - DB_USERNAME=<DB_USERNAME>
      - DB_PASSWORD=<DB_PASSWORD>
      - DB_HOST=<DB_HOST>
      - DB_PORT=<DB_PORT>
      - DB_NAME=<DB_NAME>
    networks:
      - user_module_network

networks:
  user_module_network:
    driver: bridge
