# Generated by Django 4.2.4 on 2024-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('user_id', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='用户的id')),
                ('history_list', models.TextField(default='', verbose_name='用户的搜索历史')),
            ],
            options={
                'db_table': 'user_history',
            },
        ),
    ]
