# Generated by Django 4.2.4 on 2024-12-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户的id')),
                ('list_name', models.CharField(max_length=255, verbose_name='列表名称')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'db_table': 'mark_lists',
            },
        ),
        migrations.CreateModel(
            name='MarkRelationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(default='', max_length=50, verbose_name='OpenAlexID')),
                ('mark_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_list', to='mark.mark', verbose_name='标记列表ID')),
            ],
            options={
                'db_table': 'mark_relationships',
            },
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['user_id'], name='mark_lists_user_id_a08fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='mark',
            index=models.Index(fields=['list_name'], name='mark_lists_list_na_4de638_idx'),
        ),
        migrations.AddIndex(
            model_name='markrelationships',
            index=models.Index(fields=['work_id'], name='mark_relati_work_id_b31ebb_idx'),
        ),
    ]
