# Generated by Django 4.2.4 on 2024-12-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '000100_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
