# Generated by Django 5.1.4 on 2024-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newworks',
            name='created_time',
        ),
        migrations.AddField(
            model_name='newworks',
            name='publication_date',
            field=models.DateTimeField(default=1, verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newworks',
            name='work_title',
            field=models.CharField(default=1, max_length=1000, verbose_name='文章题目'),
            preserve_default=False,
        ),
    ]
