name: User Module CI

on:
  push:
    branches:
      - main
      - dev-user
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "dev"
      SQLALCHEMY_DATABASE_URI: "sqlite:///:memory:"
    defaults:
      run:
        working-directory: ./services/user
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest tests --cov --cov-report=xml:user-module-coverage-${{ matrix.python-version }}.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: user-module-coverage-report-${{ matrix.python-version }}
          path: user-module-coverage-${{ matrix.python-version }}.xml
          retention-days: 3
        if: ${{ always() }}
